### ISSUE TITLE
数据标注

### ISSUE THREAD

**Issue by crack-dawn** [xiayuanzhang/yPlot#3]
![image](https://github.com/xiayuanzhang/yPlot/assets/99880684/b97b2558-0f05-41fd-99cc-c6455d77168e)
这个显示数据的位置可以和数据名称粘连在一块， 都一直固定在左上角好一点，不然数据多了，还得自己一一对应， 容易出错

**Comment by xiayuanzhang** [comment]
很好的建议, 下一个版本做
