### ISSUE TITLE
linux版本

### ISSUE THREAD

**Issue by tcotu** [xiayuanzhang/yPlot#4]
请问可以开发一下linux版本嘛
ubuntu做开发需要来回换系统
或者您告诉我怎么编译linux软件

**Comment by xiayuanzhang** [comment]
我没有尝试在linux环境下编译过. 但是QT是跨平台的, 并且我全部使用的QT相关库, 所以你可以在linux环境下安装一个Qt5.9.8使用gcc尝试编译一下.
